pipeline:
  name: NodeJS-CI-CD-Pipeline
  identifier: NodeJS_CI_CD_Pipeline
  projectIdentifier: CI_CD_Pipeline
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build_and_Push
        identifier: Build_and_Push
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: Docker
            spec:
              connectorRef: docker_connector
              image: node:18
              privileged: true
              resources:
                limits:
                  memory: 2Gi
                  cpu: "1"
          execution:
            steps:
              # Step 1: Install dependencies
              - step:
                  type: Run
                  name: Install Dependencies
                  spec:
                    shell: sh
                    command: |
                      npm install
              
              # Step 2: Run unit tests (no localhost server)
              - step:
                  type: Run
                  name: Run Unit Tests
                  spec:
                    shell: sh
                    command: |
                      # Ensure tests do not hit localhost
                      npm test
              
              
              # Step 3: Build and push Docker image
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Docker Image
                  spec:
                    connectorRef: docker_connector
                    repo: aaayushanand/nodejs-ci-app
                    tags:
                      - latest
                    dockerfile: dockerfile
